export const metadata = {
  title: "Terms & Privacy — StudyHack (Beta)",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-10">
      <div className="prose prose-sm max-w-none dark:prose-invert">
        <h1>Terms of Service &amp; Privacy — Closed Beta</h1>
        <p className="text-muted-foreground">
          StudyHack is in closed beta. This is a placeholder policy for beta
          testers and will be replaced before any public launch.
        </p>

        <h2>What this is</h2>
        <p>
          StudyHack is an AI study assistant scoped to a specific course. It
          answers questions grounded in the materials uploaded for that course
          and generates study aids from them.
        </p>

        <h2>What we collect</h2>
        <ul>
          <li>
            Account info from our auth provider (Clerk): your email and name.
          </li>
          <li>
            Materials you upload (files and their extracted text), your
            questions, and the AI&apos;s answers.
          </li>
          <li>Basic usage needed to operate and debug the service.</li>
        </ul>

        <h2>How uploaded materials are shared</h2>
        <p>
          <strong>
            Materials you upload to a course are added to that course&apos;s
            shared knowledge base and may be used to answer questions for other
            students enrolled in the same course.
          </strong>{" "}
          Only upload materials you have the right to share. Do not upload
          content you do not own or that a copyright holder has not permitted you
          to share.
        </p>

        <h2>AI answers are not authoritative</h2>
        <p>
          Answers are generated by an AI model and can be incomplete or wrong.
          They are a study aid, not official course guidance. Always verify
          against your professor&apos;s materials and course policies.
        </p>

        <h2>Data deletion</h2>
        <p>
          You can leave a course and delete materials you uploaded. To request
          deletion of your account and associated data during the beta, contact
          us at the address below.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms or your data: {""}
          <span className="text-muted-foreground">
            (beta contact — to be provided)
          </span>
          .
        </p>
      </div>
    </main>
  );
}
